### ISSUE TITLE
The `desc_file` arg doesn't work

### ISSUE THREAD

**Issue by thesofakillers** [WecoAI/aideml#6]
when running something like 

```python
aide data_dir="my_data_dir" desc_file="my_task_description.txt"
```

you get this:

```
Traceback (most recent call last):
  File "/Users/thesofakillers/miniconda3/envs/aide/bin/aide", line 8, in <module>
    sys.exit(run())
  File "/Users/thesofakillers/miniconda3/envs/aide/lib/python3.10/site-packages/aide/run.py", line 59, in run
    task_desc = load_task_desc(cfg)
  File "/Users/thesofakillers/miniconda3/envs/aide/lib/python3.10/site-packages/aide/utils/config.py", line 154, in load_task_desc
    with open() as f:
TypeError: open() missing required argument 'file' (pos 1)
```

seems like the file is never even give to `open()`

ill open a PR if i have the time

**Comment by yuxiang-wu** [comment]
thanks for the fix!
